version: '3'
services:    
  captcha:
    image: gtsh77workshop/grpc-captcha:v0.9.0
    # build:
    #   dockerfile: Dockerfile.service.local
    #   context: .
    env_file: 
      - .deploy/env/local.env
    environment:
      CAPTCHA_REDIS_HOST: redis
    ports:
      - 1111:1111      
      - 2222:2222      
    networks:
      default:  
    restart: on-failure:5
    depends_on:
      redis:
        condition: service_healthy  
  redis:
    image: gtsh77workshop/redis:7.2-alpine
    restart: on-failure:5   
    ports:
      - "6379:6379"
    volumes:
      - 'vredis:/data:rw'
    environment:
      TZ: 'UTC'      
    entrypoint: redis-server --save 60 1000 --loglevel warning --maxmemory 64mb --requirepass YQ3dvPx3fVzv
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "YQ3dvPx3fVzv", "ping" ]
      start_period: 3s
      interval: 1s
      timeout: 1s
      retries: 3    
    networks:
      default:
networks:
  default:
volumes:
  vredis:
