version: '3'
services:     
  captcha:
    image: gtsh77workshop/grpc-captcha:v1.0.0
    # build:
    #   dockerfile: Dockerfile.service
    #   context: .
    environment:
      CAPTCHA_RUNTIME_IS_DEV_MODE: false
      CAPTCHA_LOG_LEVEL: 0
      CAPTCHA_LOG_AS_JSON: true
      CAPTCHA_HTTP_DOMAIN_NAMES: "*"
      CAPTCHA_HTTP_HOST: 0.0.0.0
      CAPTCHA_HTTP_PORT: 1111
      CAPTCHA_HTTP_TIMEOUT: 10s
      CAPTCHA_HTTP_ENABLE_PPROF: false
      CAPTCHA_HTTP_ENABLE_PROM: true
      CAPTCHA_HTTP_METRIC_PATH: /metrics
      CAPTCHA_HTTP_HEALTH_PATH: /health/check
      CAPTCHA_HTTP_READY_PATH: /health/operable
      CAPTCHA_HTTP_TLS_ENABLED: true
      CAPTCHA_HTTP_TLS_DOMAIN_NAME: captcha.secure.nd
      CAPTCHA_HTTP_TLS_CRT_DATA: $CAPTCHA_HTTP_TLS_CRT_DATA
      CAPTCHA_HTTP_TLS_KEY_DATA: $CAPTCHA_HTTP_TLS_KEY_DATA
      CAPTCHA_HTTP_TLS_CRT_CA_DATA: $CAPTCHA_HTTP_TLS_CRT_CA_DATA  
      CAPTCHA_GRPC_HOST: 0.0.0.0
      CAPTCHA_GRPC_PORT: 2222
      CAPTCHA_GRPC_TIMEOUT: 10s
      CAPTCHA_GRPC_X_API_KEY: 1ace3bed-3aaf-4642-adb1-d63aef85895f
      CAPTCHA_GRPC_ENABLE_PROM: true
      CAPTCHA_GRPC_TLS_ENABLED: true
      CAPTCHA_GRPC_TLS_DOMAIN_NAME: captha.secure.nd
      CAPTCHA_GRPC_TLS_CRT_DATA: $CAPTCHA_GRPC_TLS_CRT_DATA
      CAPTCHA_GRPC_TLS_KEY_DATA: $CAPTCHA_GRPC_TLS_KEY_DATA
      CAPTCHA_GRPC_TLS_CRT_CA_DATA: $CAPTCHA_GRPC_TLS_CRT_CA_DATA
      CAPTCHA_REDIS_HOST: redis-master-tls.secure.nd
      CAPTCHA_REDIS_PORT: 6379
      CAPTCHA_REDIS_DB: 0
      CAPTCHA_REDIS_USER: 
      CAPTCHA_REDIS_PASS: YQ3dvPx3fVzv
      CAPTCHA_REDIS_MAX_EXEC_TIME: 3s
      CAPTCHA_REDIS_MAX_RETRIES: 2
      CAPTCHA_REDIS_MAX_IDLE_CONN: 5
      CAPTCHA_REDIS_MAX_OPEN_CONN: 25
      CAPTCHA_REDIS_MAX_CONN_TTL: 1h
      CAPTCHA_REDIS_TLS_ENABLED: true
      CAPTCHA_REDIS_TLS_DOMAIN_NAME: captcha.secure.nd
      CAPTCHA_REDIS_TLS_CRT_DATA: $CAPTCHA_REDIS_TLS_CRT_DATA 
      CAPTCHA_REDIS_TLS_KEY_DATA: $CAPTCHA_REDIS_TLS_KEY_DATA
      CAPTCHA_REDIS_TLS_CRT_CA_DATA: $CAPTCHA_REDIS_TLS_CRT_CA_DATA 
      CAPTCHA_RENDER_TTL: 1m
      CAPTCHA_RENDER_DIG_CNT: 4
      CAPTCHA_RENDER_WIDTH: 180
      CAPTCHA_RENDER_HEIGHT: 80
    ports:
      - 1111:1111      
      - 2222:2222      
    networks:
      default:  
        aliases:
          - captcha.secure.nd           
    restart: on-failure:5
    depends_on:
      redis:
        condition: service_healthy  
  redis: &rd
    user: "redis:redis"
    build:
      dockerfile: Dockerfile.redis
      context: .  
    restart: on-failure:5   
    ports:
      - "6379:6379"
    volumes:
      - 'vredis:/data:rw'
    environment:
      TZ: 'UTC'
    entrypoint: redis-server --dir /db --save 10 1 --loglevel warning --maxmemory 128mb --requirepass YQ3dvPx3fVzv --tls-port 6379 --port 0 --tls-cert-file /crt/server.crt --tls-key-file /crt/server.key --tls-ca-cert-file /crt/ca.crt --tls-protocols "TLSv1.2 TLSv1.3"
    healthcheck:
      test: [ "CMD", "redis-cli", "--tls", "--cacert", "/crt/ca.crt", "--cert", "/crt/server.crt", "--key", "/crt/server.key", "-a", "YQ3dvPx3fVzv", "ping" ]
      start_period: 3s
      interval: 1s
      timeout: 1s
      retries: 3
    networks:
      default:
        aliases:
          - redis-master-tls.secure.nd        
networks:
  default:
volumes:
  vpostgres:
  vredis:
