version: '3'
services:     
  captcha:
    image: gtsh77workshop/grpc-captcha:v0.9.1
    # build:
    #   dockerfile: Dockerfile.service
    #   context: .
    env_file: 
      - .deploy/env/local.env
    environment:
      CAPTCHA_REDIS_HOST: redis-master-tls.secure.nd
      CAPTCHA_HTTP_TLS_ENABLED: true
      CAPTCHA_HTTP_TLS_DOMAIN_NAME: captcha.secure.nd
      CAPTCHA_HTTP_TLS_CRT_DATA: $CAPTCHA_HTTP_TLS_CRT_DATA
      CAPTCHA_HTTP_TLS_KEY_DATA: $CAPTCHA_HTTP_TLS_KEY_DATA
      CAPTCHA_HTTP_TLS_CRT_CA_DATA: $CAPTCHA_HTTP_TLS_CRT_CA_DATA      
      CAPTCHA_GRPC_TLS_ENABLED: true
      CAPTCHA_GRPC_TLS_DOMAIN_NAME: captha.secure.nd
      CAPTCHA_GRPC_TLS_CRT_DATA: $CAPTCHA_GRPC_TLS_CRT_DATA
      CAPTCHA_GRPC_TLS_KEY_DATA: $CAPTCHA_GRPC_TLS_KEY_DATA
      CAPTCHA_GRPC_TLS_CRT_CA_DATA: $CAPTCHA_GRPC_TLS_CRT_CA_DATA
      CAPTCHA_REDIS_TLS_ENABLED: true
      CAPTCHA_REDIS_TLS_DOMAIN_NAME: captcha.secure.nd
      CAPTCHA_REDIS_TLS_CRT_DATA: $CAPTCHA_REDIS_TLS_CRT_DATA 
      CAPTCHA_REDIS_TLS_KEY_DATA: $CAPTCHA_REDIS_TLS_KEY_DATA
      CAPTCHA_REDIS_TLS_CRT_CA_DATA: $CAPTCHA_REDIS_TLS_CRT_CA_DATA 
    ports:
      - 1111:1111      
      - 2222:2222      
    networks:
      default:  
        aliases:
          - captcha.secure.nd           
    restart: on-failure:5
    depends_on:
      redis:
        condition: service_healthy  
  redis: &rd
    user: "redis:redis"
    build:
      dockerfile: Dockerfile.redis
      context: .  
    restart: on-failure:5   
    ports:
      - "6379:6379"
    volumes:
      - 'vredis:/data:rw'
    environment:
      TZ: 'UTC'
    entrypoint: redis-server --dir /db --save 10 1 --loglevel warning --maxmemory 128mb --requirepass YQ3dvPx3fVzv --tls-port 6379 --port 0 --tls-cert-file /crt/server.crt --tls-key-file /crt/server.key --tls-ca-cert-file /crt/ca.crt --tls-protocols "TLSv1.2 TLSv1.3"
    healthcheck:
      test: [ "CMD", "redis-cli", "--tls", "--cacert", "/crt/ca.crt", "--cert", "/crt/server.crt", "--key", "/crt/server.key", "-a", "YQ3dvPx3fVzv", "ping" ]
      start_period: 3s
      interval: 1s
      timeout: 1s
      retries: 3
    networks:
      default:
        aliases:
          - redis-master-tls.secure.nd        
networks:
  default:
volumes:
  vpostgres:
  vredis:
