version: '3'
services:    
  redis:
    image: redis:7.2-alpine
    restart: on-failure:5   
    ports:
      - "6379:6379"
    volumes:
      - 'vredis:/data:rw'
    environment:
      TZ: 'UTC'      
    entrypoint: redis-server --save 60 1000 --loglevel warning --maxmemory 64mb --requirepass YQ3dvPx3fVzv
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "YQ3dvPx3fVzv", "ping" ]
      start_period: 3s
      interval: 1s
      timeout: 1s
      retries: 3    
    networks:
      default:
        aliases: 
         - redis-master.sso.secure.nd
networks:
  default:
volumes:
  vredis:
